WIP DRAFT E&S Update
honeycombio/honeycomb-opentelemetry-java pull request #255
Opened 2022-02-01 18:53 UTC by JamieDanielson

## Which problem is this PR solving?

-

## Short description of the changes

-

2022-02-01 18:54 UTC, robbkidd commented on common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
> +        return key.matches("^[0-9a-fA-F]{32}$");
Like we discussed out-of-band, we might dial this down to a simple length check.

2022-02-01 18:59 UTC, robbkidd commented on common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
> +            System.out.printf("WARN: %s%n", getErrorMessage("service name", SERVICE_NAME));
We'll need to add our additional info about why to set service name here. Maybe we have a different way to declare the warning message strings once now that we want to say different things in the warnings about different settings?

2022-02-02 11:08 UTC, MikeGoldsmith requested changes
Added a couple of suggestions around trying to simplify logic but changes look good in general 👍🏻

2022-02-02 11:08 UTC, MikeGoldsmith commented on common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
> +        if (!isPresent(serviceName)) {
It would be nice if the warns were combined with the setting of headers below so we're not checking things multiple times. See suggestion below.

2022-02-02 19:26 UTC, robbkidd commented on common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
> +                    header += String.format("%s=%s", HONEYCOMB_DATASET_HEADER, dataset);
With this string append, I _think_ we need a comma at the beginning to separate the two headers.

```suggestion
                    header += String.format(",%s=%s", HONEYCOMB_DATASET_HEADER, dataset);
```

2022-02-09 11:20 UTC, MikeGoldsmith approved these changes

2022-02-09 19:29 UTC, merged